name: Leptos CI

on:
  pull_request:
    branches: [main]

jobs:
  lint-type:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: leptos
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('leptos/Cargo.lock') }}
      - run: cargo fmt -- --check
      - run: cargo check

  unit-mutation:
    runs-on: ubuntu-latest
    needs: lint-type
    defaults:
      run:
        working-directory: leptos
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: cargo test --all

  e2e-visual:
    runs-on: ubuntu-latest
    needs: unit-mutation
    defaults:
      run:
        working-directory: leptos
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: echo "TODO: run e2e tests"

  performance:
    runs-on: ubuntu-latest
    needs: e2e-visual
    defaults:
      run:
        working-directory: leptos
    steps:
      - uses: actions/checkout@v3
      - run: echo "TODO: add performance checks"
